//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrtmWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int Id { get; set; }
        public string Mac { get; set; }
        public string Hostname { get; set; }
        public string Ipaddr { get; set; }
        public string Netmask { get; set; }
        public string Gateway { get; set; }
        public string Dns1 { get; set; }
        public string Dns2 { get; set; }
    }
}
